### ISSUE TITLE
 steps to release a new version on CRAN

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/isomemo-data#10]
In this context, it will be necessary to update the package on CRAN after we have updated the API package. Could you check which steps must be done to release a new version on CRAN?

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/iso-app/issues/103#issuecomment-1441525501_

**Comment by jan-abel-inwt** [comment]
Package was submitted to CRAN see:

```
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/home/ljabel/Dokumente/git-work/mpi/isomemo-data/DESCRIPTION’ ...
─  preparing ‘IsoMemo’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (23.2s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘IsoMemo_23.10.0.tar.gz’
   
── Submitting ──────────────────────────────────────────────────────────────────────────────────────
ℹ Path /tmp/RtmpThlJrY/IsoMemo_23.10.0.tar.gz
ℹ File size: 24.4 Kb

Ready to submit IsoMemo (23.10.0) to CRAN?

1: No
2: Nope
3: Of course

Auswahl: 3
ℹ Uploading package & comments
ℹ Confirming submission
✔ Package submission successful
ℹ Check your email for confirmation link.
✔ Setting active project to '/home/ljabel/Dokumente/git-work/mpi/isomemo-data'
! Don't forget to tag this release once accepted by CRAN
✔ Setting active project to '<no active project>'
```

**Comment by jan-abel-inwt** [comment]
- [ ] We need to fix or documentation before the resubmission:

> Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      getDatabaseList.Rd: \value
      getMappings.Rd: \value
>
>Please fix and resubmit.

**Comment by jan-abel-inwt** [comment]
The package has been resubmitted to cran with the latest fixes.

**Comment by jan-abel-inwt** [comment]
Package has been published on CRAN and can be found [here](https://cran.r-project.org/web/packages/IsoMemo/index.html)

> Dear package maintainer,
>
> this notification has been generated automatically.
Your package IsoMemo_23.10.1.tar.gz has been built for Windows and
will be published within 24 hours in the corresponding CRAN directory.
R version 4.3.2 (2023-10-31 ucrt)
>
> All the best,
Uwe Ligges
(Maintainer of binary packages for Windows)

**Comment by arunge** [comment]
@isomemo Please note, the CRAN package 

  **IsoMemo: Retrieve Data using the 'IsoMemo' API**

 was updated (regarding the new parameter `mapping`) and re-published on CRAN.
