### ISSUE TITLE
Update functionality regarding the mappingId

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/isomemo-data#11]
- [ ] integrate the parameter `mappingId` into the functions of this package
  compare: https://github.com/Pandora-IsoMemo/data-tools/blob/main/R/03-isomemoAPI.R
- [ ] use functions from the `IsoMemo` package instead of those from `DataTools` in the `iso-app`
- remove duplicated code from `DataTools`: 
  -> https://github.com/Pandora-IsoMemo/data-tools/issues/53

**Comment by jan-abel-inwt** [comment]
closed by https://github.com/Pandora-IsoMemo/isomemo-data/pull/12
