### ISSUE TITLE
IsomemoData Name Change, Instructionss and R version

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/isomemo-data#2]
Can we change the package name from IsomemoData to IsoMemo? 

When I try to install it I get this warning: Warning message:
"package ‘IsomemoData’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages"

I have version 4.1 which is not the most recent but not that old. Why should not it work for 4.1? What about when new versions beyond 4.1.3 are released? Will it work?

In the instructions the instruction to install devtools is a comment.

**Comment by jroachell15** [comment]
@wahani You are the expert at this, I think we should think of the name change in these ways:

Display: just in github or when the user installs the package: `install.packages("IsoMemo")` not _IsomemoData_

Package Dependencies: are there any current dependencies we need to worry about?

When we get the green light from Sebastian, I think we can go ahead and change the official CRAN package name to `IsoMemo`. 

@isomemo we have talked about the R versions. Your version is fine, but do try to update your R version if you want.

**Comment by wahani** [comment]
> When we get the green light from Sebastian, I think we can go ahead and change the official CRAN package name to IsoMemo.

I don't see any problems with this, as long as the package is not on CRAN yet.

> Package Dependencies: are there any current dependencies we need to worry about?

Dependencies are listed in https://github.com/Pandora-IsoMemo/isomemo-data/blob/main/DESCRIPTION and I don't foresee any problems with them -- all on CRAN.

> Display: just in github or when the user installs the package: install.packages("IsoMemo") not IsomemoData

That's fine for me. We then should also rename the GitHub repository.
