### ISSUE TITLE
Make the new version available on CRAN

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/isomemo-data#9]
Only after completion of:
- https://github.com/Pandora-IsoMemo/data-tools/issues/35
- https://github.com/Pandora-IsoMemo/isomemo-data/issues/8
- https://github.com/Pandora-IsoMemo/isomemo-data/issues/11
- Update the maintainer in Description 
- https://github.com/Pandora-IsoMemo/isomemo-data/issues/10

To-Dos:
- [x] When all updates regarding the API have been finished a new version should be available on CRAN

**Comment by jan-abel-inwt** [comment]
see [here](https://github.com/Pandora-IsoMemo/isomemo-data/issues/10) for details
